import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import {Transaction, SimilarTransaction} from "./api/compare-wallets";
import { useAccount } from 'wagmi';

const Modal: React.FC<{
  isOpen: boolean;
  onClose: () => void;
  children: React.ReactNode;
}> = ({ isOpen, onClose, children }) => {
  useEffect(() => {
    const handleEsc = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleEsc);
    return () => window.removeEventListener('keydown', handleEsc);
  }, [onClose]);

  if (!isOpen) return null;

  return (
    <div className={styles.modalOverlay} onClick={onClose}>
      <div className={styles.modalContent} onClick={e => e.stopPropagation()}>
        <button className={styles.closeButton} onClick={onClose}>&times;</button>
        {children}
      </div>
    </div>
  );
};

const Home: NextPage = () => {
  const [inputAddress, setInputAddress] = useState('');
  const [similarWallets, setSimilarWallets] = useState<{[key: string]: number}>({});
  const [loading, setLoading] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);
  const [selectedWallet, setSelectedWallet] = useState('');
  const [similarTransactions, setSimilarTransactions] = useState<SimilarTransaction[]>([]);
  const [compareLoading, setCompareLoading] = useState(false);
  
  const { address } = useAccount();

  const handleCheckSimilarWallets = async () => {
    setLoading(true);
    try {
      const response = await fetch('/api/wallet', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ address: inputAddress }),
      });
      const data = await response.json();
      setSimilarWallets(data.similarWallets);
    } catch (error) {
      console.error('Error checking similar wallets:', error);
    }
    setLoading(false);
  };

  const handleCheckSimilarWalletsForAccount = async() => {
    setInputAddress(address as string);
    await handleCheckSimilarWallets();
  }

  const handleCompareWallets = async (similarWalletAddress: string) => {
    setSelectedWallet(similarWalletAddress);
    setModalOpen(true);
    setCompareLoading(true);
    try {
      const response = await fetch('/api/compare-wallets', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ wallet1: address, wallet2: similarWalletAddress }),
      });
      const data = await response.json();
      setSimilarTransactions(data.similarTransactions);
    } catch (error) {
      console.error('Error comparing wallets:', error);
    }
    setCompareLoading(false);
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>Similar Wallets</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <div className={styles.grid}>
        <div className={styles.card}>
            <button
              onClick={handleCheckSimilarWalletsForAccount}
              disabled={loading}
              className={styles.button}
            >
              {loading ? 'Checking...' : 'Check Similar Wallets for my account!'}
            </button>
          </div>
          <div className={styles.card}>
            <input
              type="text"
              value={inputAddress}
              onChange={(e) => setInputAddress(e.target.value)}
              placeholder="Enter Ethereum address"
              className={styles.input}
            />
            <button
              onClick={handleCheckSimilarWallets}
              disabled={loading}
              className={styles.button}
            >
              {loading ? 'Checking...' : 'Check Similar Wallets'}
            </button>
          </div>
          {loading ? (<p>Loading similar wallets...</p>) : 
          similarWallets && Object.keys(similarWallets).length > 0 ? (
            <div className={styles.grid}>
              {Object.entries(similarWallets).map(([walletAddress, count]) => (
                <div key={walletAddress} className={styles.card} onClick={() => handleCompareWallets(walletAddress)}>
                  <h3>Wallet Address:</h3>
                  <p>{walletAddress}</p>
                  <p>Similar Transactions: {count}</p>
                </div>
              ))}
            </div>
          ) : (
            <p>Great! No similar wallets found.</p>
          )}
        </div>

        <Modal isOpen={modalOpen} onClose={() => setModalOpen(false)}>
          {compareLoading ? <h2>Similar Transactions</h2> : <h2>{similarTransactions.length} Similar Transactions</h2>}
          <p>Comparing {inputAddress} with {selectedWallet}</p>
          {compareLoading ? (
            <p>Loading comparison data...</p>
          ) : similarTransactions.length > 0 ? (
            <ul className={styles.transactionList}>
              {similarTransactions.map((tx, index) => (
                <li key={index} className={styles.transactionItem}>
                  <p><strong>Contract:</strong> {tx.contractAddress}</p>
                  <p><strong>Method 1:</strong> {tx.wallet1Tx.input.slice(0, 10)}</p>
                  <p><strong>Method 2:</strong> {tx.wallet2Tx.input.slice(0, 10)}</p>
                  <p><strong>Value 1:</strong> {parseInt(tx.wallet1Tx.value, 10) / 1e18} ETH</p>
                  <p><strong>Value 1:</strong> {parseInt(tx.wallet2Tx.value, 10) / 1e18} ETH</p>
                  <p>
                    <strong>Wallet 1 Tx: </strong> 
                    <a href={`https://scrollscan.com/tx/${tx.wallet1Tx.hash}`} target="_blank" rel="noopener noreferrer">
                      {`https://scrollscan.com/tx/${tx.wallet1Tx.hash}`}
                    </a>
                  </p>
                  <p>
                    <strong>Wallet 2 Tx: </strong> 
                    <a href={`https://scrollscan.com/tx/${tx.wallet2Tx.hash}`} target="_blank" rel="noopener noreferrer">
                      {`https://scrollscan.com/tx/${tx.wallet2Tx.hash}`}
                    </a>
                  </p>
                  <p><strong>Time 1:</strong> {new Date(parseInt(tx.wallet1Tx.timeStamp) * 1000).toLocaleString()}</p>
                  <p><strong>Time 2:</strong> {new Date(parseInt(tx.wallet2Tx.timeStamp) * 1000).toLocaleString()}</p>
                  <p><strong>Time difference:</strong> {Math.abs(parseInt(tx.wallet1Tx.timeStamp) - parseInt(tx.wallet2Tx.timeStamp))} seconds</p>
                </li>
              ))}
            </ul>
          ) : (
            <p>No similar transactions found.</p>
          )}
        </Modal>
      </main>
    </div>
  );
};

export default Home;